# Setup
title: Shane Nguyen
description: Researcher at DEVCOM Army Research Laboratory
url: https://shanenn.github.io
avatar: /_images/avatar.jpg
paginate: 5
permalink: pretty
cover_image: /_images/background.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
logo: logo.png
social:
  name: Shane Nguyen
  links:
    - https://www.linkedin.com/in/shane--nguyen/
    - https://github.com/shanenn/
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Shane Nguyen
  url: https://github.com/shanenn/
  email: shanennguyen@gmail.com
